<!-- /**
 * Digit Software Solutions..
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category   Dss
 * @package    Dss_SalesOrderGrid
 * @author     Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */ -->
<?php
/** @var $block \Dss\SalesOrderGrid\Block\Adminhtml\System\Config\Form\Fieldset\Support */
?>
<div class="mp-system-module-info-wrapper">
    <img src="https://www.Dss.com/_logo.svg" alt="Dss" style="height: 50px;">
    <p style="margin: 0;">
        <strong class="mp-module-info-meta">
            <?= /* @noEscape */ $block->getExtensionName() ?>
                <sup style="font-size: 80%;">v<?= /* @noEscape */ $block->getModuleVersion() ?>
                </sup> <?= /* @noEscape */ __('by') ?>
        </strong>
        <a target="_blank" href="https://www.Dss.com"
            title="Dss Store - Free / Premium Magento Extensions,  Themes &amp; Services">
            <strong>Dss</strong>
        </a>
    </p>
    <div class="mp-module-info-content">
        <p>
            <?= /* @noEscape */ __('If you need any support or have feedback, please') ?>
                <a href="https://www.Dss.com/contact" class="mp-module-info-link mp-reddish"
                    target="_blank" title="Dss Store - Contact Us"><?= /* @noEscape */ __('contact us') ?></a>
        </p>
        <p>
            <?= /* @noEscape */ __('Also, feel free to browse our') ?>
                <a href="https://www.Dss.com/extensions/magento-2.html" class="mp-module-info-link mp-bluish"
                target="_blank" title="Dss Store - Free / Premium Magento Extensions,  Themes &amp; Services">store</a>
                <?= /* @noEscape */ __('for more extensions.') ?>
        </p>

    </div>
</div>
